#!/usr/bin/env bash
set -xeu

# the current (real) directory, could be ~/.dotfiles, could be ~/src/github.com/jonpulsifer/dotfiles
dotfiles=$( dirname "$( realpath -s "${BASH_SOURCE[0]}" )" )

# we need wget to go brr
ensure_dependencies() {
  local -r deps="wget"
  for file in ${deps}; do
    command -v ${file} || { echo -e "${file} not found.\nEnsure ${file} is installed and in your PATH"; exit 1; } ;
  done
}

# source the nix profile and ensure `nix` is found
load_nix() {
  # shellcheck disable=1090
  source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
  command -v nix
}

# sudo pipe bash for the win + initalize nixpkgs
install_nix() {
  command -v nix || wget -qO - https://nixos.org/nix/install | sh
  if [ -d "${HOME}/.config/nixpkgs" ] || [ -L "${HOME}/.config/nixpkgs" ]; then
    echo ':( ~/.config/nixpkgs exists, you might not want to delete it'
    exit 1
  else
    ln -fvs "${dotfiles}/nix" ~/.config/nixpkgs;
  fi
  load_nix && nix-channel --update
}

# install home-manager if not found and run `home-manager switch`
install_dotfiles() {
  command -v home-manager || nix-env -iA 'nixpkgs.home-manager'
  home-manager switch -b '.bak'
}

# brrr
ensure_dependencies
load_nix || install_nix
install_dotfiles
